version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: analytics-node
    versions:
    - 3.5.0
    - 4.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: grunt-contrib-uglify
    versions:
    - 5.0.0
